add image field to CustomSession
DavayPosmotrim/dv-backend pull request #55
Opened 2024-07-17 11:06 UTC by LynnG3

- добавила поле image в модель CustomSession и сериализатор сессии
- добавила  методы  update, perform_update и update_session_image в CustomSessionViewSet. Сейчас там отражено только обнолвение поля  image, но как я понимаю там же надо будет обрабатывать изменения полей `status` и `matched_movies`

2024-07-19 12:40 UTC, YaStirayuLaskoy requested changes
Есть пара моментов

2024-07-19 12:40 UTC, YaStirayuLaskoy commented on backend/api/views.py
> +        return super().update(request, *args, **kwargs)
Методы _create_ и _update_ переопределены, но фактически они просто вызывают методы суперкласса без какой-либо логики. Это, вроде, можно убрать

2024-07-19 12:40 UTC, YaStirayuLaskoy commented on backend/api/views.py
> +                session.save()
Насколько я понимаю, тут делается запрос для каждого обновления сессии. Вместо того, чтобы каждый раз запрашивать _matched_movies_, можно сохранять результат запроса в переменной и объединить их

Что то типа такого:
```python
def update_session_image(self, session: CustomSession) -> None:
    if session.status == 'closed':
        matched_movies: List[Movie] = list(session.matched_movies.all())  # Загружаем заранее
        if matched_movies.exists():
            top_movie = matched_movies.order_by('-rating_kp').first()
            if top_movie and top_movie.poster:
                session.image = top_movie.poster
                session.save()
```

Это не критично, так как по факту, убирает лишь один лишний запрос к БД, но я бы сделал так :D

2024-07-19 12:40 UTC, YaStirayuLaskoy commented on backend/api/views.py
> +        self.update_session_image(session)
Было бы круто добавить типизацию

```python
def perform_update(self, serializer: CustomSessionCreateSerializer) -> None:
    session: CustomSession = serializer.save()
    self.update_session_image(session)
```

2024-07-19 17:50 UTC, LynnG3 commented on backend/api/views.py
> +        return super().update(request, *args, **kwargs)
да, это просто методы суперкласса, но я добавила их для подключения схем для сваггера, чтобы там шаблон тела запроса формировался корректно, без лишних полей. Если это можно реализовать иначе - подскажи плиз

2024-07-19 17:51 UTC, LynnG3 commented on backend/api/views.py
> +                session.save()
Ок

2024-07-19 17:56 UTC, LynnG3 commented on backend/api/views.py
> +        self.update_session_image(session)
Тогда надо определиться - добавляем ли мы типизацию по всему проекту. Если да, предлагаю это сделать отдельной задачей чтобы не тормозить процесс. @midnightrebel что думаешь?

2024-07-21 11:28 UTC, midnightrebel commented on backend/api/views.py
> +        self.update_session_image(session)
> Тогда надо определиться - добавляем ли мы типизацию по всему проекту. Если да, предлагаю это сделать отдельной задачей чтобы не тормозить процесс. @midnightrebel что думаешь?

Как вариант. В рамках этой задачи типизацию можно добавить сразу, а остальные модули можно типизировать в рамках новой задачи

2024-07-21 19:41 UTC, YaStirayuLaskoy commented on backend/api/views.py
> +        return super().update(request, *args, **kwargs)
А, это для схем. Тогда всё ок)

2024-07-22 08:55 UTC, pukhalskiy approved these changes

2024-07-22 10:31 UTC, midnightrebel approved these changes

2024-07-22 10:43 UTC, merged

2024-07-22 10:45 UTC, YaStirayuLaskoy approved these changes
Всё гуд!